tasks/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="list"),
    path('update_task/<str:pk>/', views.updatetask, name="update_task"),
    path('delete/<str:pk>/', views.deletetask, name="delete"),
]

todo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tasks.urls'))
]

tasks/models.py
from django.db import models

class Task(models.Model):
    title = models.CharField(max_length=100)
    complete = models.BooleanField(default=False)
    create = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

tasks/forms.py
from django import forms
from django.forms import ModelForm

from .models import *

class TaskForm(forms.ModelForm):

    class Meta:
        model = Task
        fields = '__all__'

tasks/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import *
from .forms import *

def index(request):
    tasks = Task.objects.all()

    form = TaskForm()

    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('/')

    context = {'tasks':tasks, 'form':form}
    return render(request, 'tasks/list.html', context)

def updatetask(request, pk):
    task = Task.objects.get(id=pk)

    form = TaskForm(instance=task)

    if request.method == 'POST':
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            form.save()
        return redirect('/')

    context = {'form':form}

    return render(request, 'tasks/update_task.html', context)

def deletetask(request, pk):
    item = Task.objects.get(id=pk)

    if request.method == 'POST':
        item.delete()
        # აბრუნებს მითითებულ html გვერდზე
        return redirect('/')

    context = {'item':item}
    return render(request, 'tasks/delete.html', context)

tasks/templates/tasks/delete.html
<p>Are you sure you want to delete "{{item}}"?</p>

<a href="{% url 'list' %}">Cancel</a>

<form method="POST" action="">
    {% csrf_token %}

    <input type="submit" name="Confirm">
</form>

tasks/templates/tasks/list.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<style>

	body{
		background-color: #638CB8;
	}

	input{
		width: 100%;
		padding: 12px 20px;
		margin: 8px 0;
		box-sizing: border-box;
	}

	input::placeholder {
	  color: #d3d3d3;
	}

	.submit{
		background-color: #6BA3E8;
	}

	.center-column{
		width:600px;
		margin: 20px auto;
		padding:20px;
		background-color: #fff;
		border-radius: 3px;
		box-shadow: 6px 2px 30px 0px rgba(0,0,0,0.75);
	}

	.item-row{
		background-color: #906abd;
		margin: 10px;
		padding: 20px;
		border-radius: 3px;
		color: #fff;
		font-size: 16px;
		box-shadow: 0px -1px 10px -4px rgba(0,0,0,0.75);
	}

	.btn-danger{
		background-color: #ffae19;
		border-color: #e59400;
	}

</style>

<div class="center-column">

    <h1>To Do App</h1>

    <form method="POST" action="/">
        {% csrf_token %}
        {{form.title}}
        <input class="btn btn-info" type="submit" name="Create Task">
    </form>

    <div class="todo-list">

    {% for task in tasks %}
        <div class="item-row">
            <a class="btn btn-sm btn-info" href="{% url 'update_task' task.id %}">
            Update</a>
            <a class="btn btn-sm btn-danger" href="{% url 'delete' task.id %}">
            Delete</a>

            {% if task.complete == True %}
            <strike>{{task}}</strike>
            {% else %}
            <span>{{task}}</span>
            {% endif %}
        </div>
    {% endfor %}
    </div>
</div>

tasks/templates/tasks/update_task.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<style>

	body{
		background-color: #638CB8;
	}

	input{
		width: 100%;
		padding: 12px 20px;
		margin: 8px 0;
		box-sizing: border-box;
	}

	input::placeholder {
	  color: #d3d3d3;
	}

	.submit{
		background-color: #6BA3E8;
	}

	.center-column{
		width:600px;
		margin: 20px auto;
		padding:20px;
		background-color: #fff;
		border-radius: 3px;
		box-shadow: 6px 2px 30px 0px rgba(0,0,0,0.75);
	}

	/*.item-row{
		background-color: #906abd;
		margin: 10px;
		padding: 20px;
		border-radius: 3px;
		color: #fff;
		font-size: 16px;
		box-shadow: 0px -1px 10px -4px rgba(0,0,0,0.75);
	}*/

	/*.btn-danger{
		background-color: #ffae19;
		border-color: #e59400;
	}*/

    /*input#id_complete{
        display: flex;
        flex-direction: row;
    }*/

    /*.center-column{*!*/
    /*    display: flex;*/
    /*    flex-direction: row;*/
    /*}*/




</style>

<div class="center-column">


<h3>Update Task</h3>

<form method="POST" action="">
    {% csrf_token %}

    {{form}}
    <input type="submit" name="Update Task">

</form>


<!--<div class="checkbox-container">-->
<!--    <input type="checkbox" name="complete" id="id_complete">-->
<!--    <label for="id_complete">Complete:</label>-->
<!--</div>-->